/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignoutRouteImport } from './routes/signout'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoutesIndexRouteImport } from './routes/routes/index'
import { Route as RoutesMyRouteImport } from './routes/routes/my'
import { Route as RoutesCreateRouteImport } from './routes/routes/create'
import { Route as PhotosSplatRouteImport } from './routes/photos/$'
import { Route as RoutesIdIndexRouteImport } from './routes/routes/$id/index'
import { Route as RoutesIdPhotosRouteImport } from './routes/routes/$id/photos'
import { Route as AuthLineCallbackRouteImport } from './routes/auth/line/callback'

const SignoutRoute = SignoutRouteImport.update({
  id: '/signout',
  path: '/signout',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesIndexRoute = RoutesIndexRouteImport.update({
  id: '/routes/',
  path: '/routes/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesMyRoute = RoutesMyRouteImport.update({
  id: '/routes/my',
  path: '/routes/my',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesCreateRoute = RoutesCreateRouteImport.update({
  id: '/routes/create',
  path: '/routes/create',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosSplatRoute = PhotosSplatRouteImport.update({
  id: '/photos/$',
  path: '/photos/$',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesIdIndexRoute = RoutesIdIndexRouteImport.update({
  id: '/routes/$id/',
  path: '/routes/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesIdPhotosRoute = RoutesIdPhotosRouteImport.update({
  id: '/routes/$id/photos',
  path: '/routes/$id/photos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLineCallbackRoute = AuthLineCallbackRouteImport.update({
  id: '/auth/line/callback',
  path: '/auth/line/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signout': typeof SignoutRoute
  '/photos/$': typeof PhotosSplatRoute
  '/routes/create': typeof RoutesCreateRoute
  '/routes/my': typeof RoutesMyRoute
  '/routes/': typeof RoutesIndexRoute
  '/auth/line/callback': typeof AuthLineCallbackRoute
  '/routes/$id/photos': typeof RoutesIdPhotosRoute
  '/routes/$id/': typeof RoutesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signout': typeof SignoutRoute
  '/photos/$': typeof PhotosSplatRoute
  '/routes/create': typeof RoutesCreateRoute
  '/routes/my': typeof RoutesMyRoute
  '/routes': typeof RoutesIndexRoute
  '/auth/line/callback': typeof AuthLineCallbackRoute
  '/routes/$id/photos': typeof RoutesIdPhotosRoute
  '/routes/$id': typeof RoutesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signout': typeof SignoutRoute
  '/photos/$': typeof PhotosSplatRoute
  '/routes/create': typeof RoutesCreateRoute
  '/routes/my': typeof RoutesMyRoute
  '/routes/': typeof RoutesIndexRoute
  '/auth/line/callback': typeof AuthLineCallbackRoute
  '/routes/$id/photos': typeof RoutesIdPhotosRoute
  '/routes/$id/': typeof RoutesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/saved'
    | '/settings'
    | '/signin'
    | '/signout'
    | '/photos/$'
    | '/routes/create'
    | '/routes/my'
    | '/routes/'
    | '/auth/line/callback'
    | '/routes/$id/photos'
    | '/routes/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/saved'
    | '/settings'
    | '/signin'
    | '/signout'
    | '/photos/$'
    | '/routes/create'
    | '/routes/my'
    | '/routes'
    | '/auth/line/callback'
    | '/routes/$id/photos'
    | '/routes/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/saved'
    | '/settings'
    | '/signin'
    | '/signout'
    | '/photos/$'
    | '/routes/create'
    | '/routes/my'
    | '/routes/'
    | '/auth/line/callback'
    | '/routes/$id/photos'
    | '/routes/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  SavedRoute: typeof SavedRoute
  SettingsRoute: typeof SettingsRoute
  SigninRoute: typeof SigninRoute
  SignoutRoute: typeof SignoutRoute
  PhotosSplatRoute: typeof PhotosSplatRoute
  RoutesCreateRoute: typeof RoutesCreateRoute
  RoutesMyRoute: typeof RoutesMyRoute
  RoutesIndexRoute: typeof RoutesIndexRoute
  AuthLineCallbackRoute: typeof AuthLineCallbackRoute
  RoutesIdPhotosRoute: typeof RoutesIdPhotosRoute
  RoutesIdIndexRoute: typeof RoutesIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signout': {
      id: '/signout'
      path: '/signout'
      fullPath: '/signout'
      preLoaderRoute: typeof SignoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes/': {
      id: '/routes/'
      path: '/routes'
      fullPath: '/routes/'
      preLoaderRoute: typeof RoutesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes/my': {
      id: '/routes/my'
      path: '/routes/my'
      fullPath: '/routes/my'
      preLoaderRoute: typeof RoutesMyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes/create': {
      id: '/routes/create'
      path: '/routes/create'
      fullPath: '/routes/create'
      preLoaderRoute: typeof RoutesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos/$': {
      id: '/photos/$'
      path: '/photos/$'
      fullPath: '/photos/$'
      preLoaderRoute: typeof PhotosSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes/$id/': {
      id: '/routes/$id/'
      path: '/routes/$id'
      fullPath: '/routes/$id/'
      preLoaderRoute: typeof RoutesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes/$id/photos': {
      id: '/routes/$id/photos'
      path: '/routes/$id/photos'
      fullPath: '/routes/$id/photos'
      preLoaderRoute: typeof RoutesIdPhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/line/callback': {
      id: '/auth/line/callback'
      path: '/auth/line/callback'
      fullPath: '/auth/line/callback'
      preLoaderRoute: typeof AuthLineCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  SavedRoute: SavedRoute,
  SettingsRoute: SettingsRoute,
  SigninRoute: SigninRoute,
  SignoutRoute: SignoutRoute,
  PhotosSplatRoute: PhotosSplatRoute,
  RoutesCreateRoute: RoutesCreateRoute,
  RoutesMyRoute: RoutesMyRoute,
  RoutesIndexRoute: RoutesIndexRoute,
  AuthLineCallbackRoute: AuthLineCallbackRoute,
  RoutesIdPhotosRoute: RoutesIdPhotosRoute,
  RoutesIdIndexRoute: RoutesIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
